CREATE TABLE "tune_order" (
	"id" text PRIMARY KEY NOT NULL,
	"order_number" text NOT NULL,
	"creem_checkout_id" text,
	"creem_customer_id" text,
	"customer_email" text NOT NULL,
	"locale" text DEFAULT 'en',
	"blackbox_filename" text,
	"blackbox_file_size" integer,
	"problems" text,
	"goals" text,
	"flying_style" text,
	"frame_size" text,
	"additional_notes" text,
	"analysis_result" jsonb,
	"cli_commands" text,
	"pdf_url" text,
	"pdf_hash" text,
	"blackbox_url" text,
	"email_sent_at" timestamp,
	"email_message_id" text,
	"email_delivered_at" timestamp,
	"status" text DEFAULT 'pending' NOT NULL,
	"amount" integer,
	"currency" text DEFAULT 'USD',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"paid_at" timestamp,
	"completed_at" timestamp,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "tune_order_order_number_unique" UNIQUE("order_number")
);
